# Generated by Django 5.0.5 on 2024-05-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
    ]
